// Code generated by DI. DO NOT EDIT.

package decorators

import (
	"reflect"

	"github.com/MaximZayats/godi/codegen"
)

var Config = codegen.Config{
	PackageName:         "decorators",
	PathToStorageFolder: `.pkg/storage/decorators`,
	StorageFileName:     "di_injection_decorators_gen.go",
	GetterFunction:      getDecorator,
}

var functions = map[string]any{}

func getDecorator(f any) (any, bool) {
	v, ok := functions[reflect.TypeOf(f).String()]
	return v, ok
}
